version: 1
runtime: python27
api_version: 1
threadsafe: true
application: henry-nelson

handlers:  
- url: /img
  static_dir: img

- url: /res
  static_dir: res

- url: /
  script: henryjnelson.app

- url: /about
  script: henryjnelson.app

- url: /prof
  script: henryjnelson.app

- url: /pubs
  script: henryjnelson.app

libraries:
- name: webapp2
  version: latest
