version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /contact
  script: henryjnelson.app

- url: /
  script: henryjnelson.app

- url: /about
  script: henryjnelson.app

- url: /mathcs
  script: henryjnelson.app

- url: /physics
  script: henryjnelson.app

- url: /philo
  script: henryjnelson.app

- url: /prof
  script: henryjnelson.app

- url: /movies
  script: henryjnelson.app

libraries:
- name: webapp2
  version: latest
